### PR TITLE
Feature: Add MotionSensor, ContactSensor and Outlet

### PR DESCRIPTION
**Pull request by marcelkordek**

### CODE REVIEW

**Comment by knalli** [comment]
@marcelkordek  Thank you for the PR.

Does there exist any difference between outlet and switch?

**Comment by marcelkordek** [comment]
Yes it is shown differently in Homekit.

bildschirmfoto-2017-09-08-um-10 22 56

I've added 'outlet' for Issue #26

**Comment by knalli** [comment]
Great. 

Danke ;)

**Comment by knalli** [comment]
Thank you again for contributing ⭐️ . Just added in master, coming soon as release.

**Pull request closed without merging**
